### ISSUE TITLE
Subprocess Error "gmx mdrun -deffnm densified-min -gpu_id 0" failed with returncode 1

### ISSUE THREAD

**Issue by ggolde** [AbramsGroup/HTPolyNet#3]
Hello, I working through setting up HTPolyNet on my Windows 11 desktop within WSL2 running Ubuntu. I was working through the tutorial for PMS and encountered this error in the console log during densification:

INFO> ********** Densification in proj-0/systems/densification **********
INFO> Running Gromacs: minimization
ERROR> Returncode: 1
ERROR> stderr buffer follows
*******************************************************
                      :-) GROMACS - gmx mdrun, 2024.1 (-:

Executable:   /usr/local/gromacs/bin/gmx
Data prefix:  /usr/local/gromacs
Working dir:  /home/griffin/mds/HTPolyNet/pms_tutorial/2-polymethylstyrene/proj-0/systems/densification
Command line:
  gmx mdrun -deffnm densified-min -gpu_id 0

-------------------------------------------------------
Program:     gmx mdrun, version 2024.1
Source file: src/gromacs/hardware/device_management_common.cpp (line 158)
Function:    bool deviceIdIsCompatible(gmx::ArrayRef<const std::unique_ptr<DeviceInformation> >, int)

Range checking error (possible bug):
Device ID 0 did not correspond to any of the 0 detected device(s)

For more information and tips for troubleshooting, please check the GROMACS
website at https://manual.gromacs.org/current/user-guide/run-time-errors.html
-------------------------------------------------------

*******************************************************
Traceback (most recent call last):
  File "/home/griffin/anaconda3/envs/amber_env/bin/htpolynet", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/driver.py", line 257, in cli
    args.func(args)
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/driver.py", line 66, in run
    a.do_workflow(force_checkin=args.force_checkin,force_parameterization=args.force_parameterization)
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/runtime.py", line 390, in do_workflow
    self.do_densification()
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/checkpoint.py", line 60, in wrapper_method
    result=method(self,*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/runtime.py", line 289, in do_densification
    self._do_equilibration_series(equilibration,deffnm=f'{deffnm}',plot_pfx='densification')
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/runtime.py", line 642, in _do_equilibration_series
    self._do_equilibration(stg,deffnm,plot_pfx)
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/runtime.py", line 625, in _do_equilibration
    edr_list=TC.equilibrate(deffnm,edict,gromacs_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/topocoord.py", line 1885, in equilibrate
    self.grompp_and_mdrun(out=f'{deffnm}-{ens}',mdp=new_mdp,quiet=False,**gromacs_dict)
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/topocoord.py", line 1751, in grompp_and_mdrun
    msg=grompp_and_mdrun(gro=gro,top=top,out=out,mdp=mdp,**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/gromacs.py", line 108, in grompp_and_mdrun
    c.run(quiet=quiet,ignore_codes=ignore_codes)
  File "/home/griffin/anaconda3/envs/amber_env/lib/python3.12/site-packages/HTPolyNet/command.py", line 31, in run
    raise subprocess.SubprocessError(f'Command "{self.c}" failed with returncode {process.returncode}')
subprocess.SubprocessError: Command "gmx mdrun -deffnm densified-min -gpu_id 0" failed with returncode 1

I believe the problem is the -gpu_id parameter. I am currently running an AMD gpu (and ROCm is not supported on WSL2) so my GROMACS currently does not have GPU support. I was looking through your documentation and could not find if HTPolyNet requires GPU support from GROMACS. I am wondering if this is the origin of the error or if it is something else. Thank you for maintaining this package!

**Comment by cameronabrams** [comment]
Hi Griffin,
Are you using v 1.0.9 of HTPolyNet?  I'm not exactly sure why the -gpu_id 0
switch is begin set for you.
Cameron

**Comment by cameronabrams** [comment]
Also, you should take a look at the YAML input file.  By default I have the
following directive in the gromacs stanza:

mdrun_options:
    gpu_id: 0

You should delete or comment out those lines in your YAML files.
